### ISSUE TITLE
LightAPRS-hab unsigned altitude conversion

### ISSUE THREAD

**Issue by ladecadence** [lightaprs/LightAPRS-1.0#1]
in the updateTelemetry() function, the conversion for the altitude is like:

`sprintf(telemetry_buff + 10, "%06lu", (long)gps.altitude.feet());`

But the altitude is a signed value, so if the altitude is negative (sometimes the GPS altitude is not that good), the value printed will be very high, something like 429496 feet.

Changing the sprintf to a signed value "%06l" fixes this.

**Comment by ladecadence** [comment]
Example:

![image](https://user-images.githubusercontent.com/211954/66568111-fb7e5f00-eb68-11e9-872b-cf27fe97210e.png)

**Comment by lightaprs** [comment]
Thanks for the feedback.

You are right about the negative altitude values but i don't think "%60l" is the right solution for both negative and positive large values. But following does, what do you think ?

  float tempAltitude = gps.altitude.feet();

  if (tempAltitude>0){
    sprintf(telemetry_buff + 10, "%06lu", (long)tempAltitude);
  } else{
    sprintf(telemetry_buff + 10, "%06d", (long)tempAltitude);
    }

**Comment by lightaprs** [comment]
Updated  as you suggested. Thanks.
