### ISSUE TITLE
aprsFreq_buf size should be 9 instead of 8

### ISSUE THREAD

**Issue by dl9sau** [lightaprs/LightAPRS-1.0#13]
In configureFreqbyLocation(), aprsFreqbuff has a size of 8. Should be 9 (for string terminator \0).
-> \0 was written beyond the array.

   ...
    GEOFENCE_position(tempLat,tempLong);  
    float dividedFreq = GEOFENCE_APRS_frequency / 1000000.f;
    char aprsFreq_buff[8];
    dtostrf(dividedFreq, 8, 4, aprsFreq_buff);
    configDra818(aprsFreq_buff);    
   ...

Fix: change aprsFreq_buff[8] to aprsFreq_buff[9] :
   ...
    char aprsFreq_buff[9];
    dtostrf(dividedFreq, 8, 4, aprsFreq_buff);
   ...

Explanation:
arg 8 of diviededFreq specifies the total number of digits to be filled in, but \0 termination is added (-> number+1).
aprs frequency is i.e. 144.800; modem expects 144.80000. Int Variable is 144800000. 
dividedFreq =  GEOFENCE_APRS_frequency / 1000000.f == 144800000 / 1000000.f == 144.8 .
dtostrf(dividedFreq, 8, 4, aprsFreq_buff) is told to set 4 digits behind '.'. Characters including '.' sould be eight. -> 3 digits room for integer 144 left of '.'. Resuling string is "144.8000", len 8, and needs \0 for completion -> aprsFreq_buf sould be size 9.

Please also correct this in the lightaprs-w project.

**Comment by lightaprs** [comment]
Thanks for the bug and fix :)
